talktoform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('usersettings', views.usersettings, name='usersettings'),
    path('editform/<int:form_template_id>/', views.editform, name='editform'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('create_default_form_template/', views.create_default_form_template, name='create_default_form_template'),
    path('form_template/<int:form_template_id>/delete/', views.delete_form_template, name='delete_form_template'),
    path('logout', views.logout, name='logout'),
    path('editform/<int:form_template_id>/edit_title/', views.edit_template_title, name='edit_template_title'),
    path('editform/<int:form_template_id>/save_title/', views.save_template_title, name='save_template_title'),
    path('editform/<int:form_template_id>/edit_template_body/', views.edit_template_body, name='edit_template_body'),
    path('editform/<int:form_template_id>/save_template_body/', views.save_template_body, name='save_template_body'),
    path('create_question/<int:form_template_id>/', views.create_question, name='create_question'),
    path('editform/<int:form_template_id>/edit_question/<int:question_id>/', views.edit_question, name='edit_question'),
    path('delete_question/<int:form_template_id>/edit_question/<int:question_id>/', views.delete_question, name='delete_question'),
    path('editform/<int:form_template_id>/save_question/<int:question_id>/', views.save_question, name='save_question'),
    path('form_template/<int:form_template_id>/save_config/', views.save_form_config, name='save_form_config'),
    path('create_form/<int:template_id>/', views.create_form, name='create_form'),
    path('upload_audio/<int:form_id>/', views.upload_audio, name='upload_audio'),
    path('stop_audio/<int:form_id>/', views.stop_audio, name='stop_audio'),
    path('response_form/<int:form_id>/', views.response_form, name='response_form'),
    path('delete_account/', views.delete_account, name='delete_account')
]

website/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.core.files.storage import default_storage
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class User(AbstractUser):
    approval = models.BooleanField(default=False)
    def __str__(self):
        return f"User ID: {self.id} | User: {self.username}"

class FormTemplate(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"FormTemplate ID: {self.id} | User: {self.user.username} | Template: {self.title}"


class Form(models.Model):
    template = models.ForeignKey(FormTemplate, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    form_template_id = models.PositiveIntegerField(default=0)
    transcript = models.TextField(default="")

    def save(self, *args, **kwargs):
        if self.pk is None:  # New form instance
            # Retrieve the count of forms based on the associated FormTemplate
            form_count = Form.objects.filter(template=self.template).count()
            # Increment the count and assign it to form_template_id
            self.form_template_id = form_count + 1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Form ID: {self.id} | User: {self.user.username} | Form: {self.template.title} #{self.form_template_id}"


class Question(models.Model):
    template = models.ForeignKey(FormTemplate, on_delete=models.CASCADE)
    question = models.CharField(max_length=255)
    editing = models.BooleanField(default=False)
    def __str__(self):
        return f"Question ID: {self.id} | User: {self.template.user.username} | Template: {self.template.title} | Question: {self.question}"

class FormResponse(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    response = models.TextField(default="Null")
    def truncated_response(self):
        if len(self.response) > 50:
            return self.response[:50] + "..."
        return self.response
    
    def __str__(self):
        return f"FormResponse ID: {self.id} | User: {self.question.template.user.username} | Form: {self.question.template.title} #{self.form.form_template_id} | Question: {self.question.question} | Response: {self.truncated_response()}"

class FormConfig(models.Model):
    AUDIO_RECOGNITION_MODEL_CHOICES = [
        ('whisper-1', 'whisper')
    ]
    AI_MODEL_CHOICES = [
        ('gpt-5', 'gpt-5'),
        ('gpt-5-mini', 'gpt-5-mini'),
        ('gpt-4.1', 'gpt-4.1'),
    ]
    form_template = models.OneToOneField('FormTemplate', on_delete=models.CASCADE)
    language = models.CharField(max_length=255, default = 'english')
    conversation_type = models.CharField(max_length=255, default='')
    audio_recognition_model_id = models.CharField(max_length=255, choices=AUDIO_RECOGNITION_MODEL_CHOICES, default='whisper-1')
    system_prompt = models.TextField(default='')
    ai_model_id = models.CharField(max_length=255, choices=AI_MODEL_CHOICES, default='gpt-5')
    temperature = models.DecimalField(max_digits=3, decimal_places=1, default=0.2, validators=[MaxValueValidator(2), MinValueValidator(-2)])
    presence_penalty = models.DecimalField(max_digits=3, decimal_places=1, default=-0.2, validators=[MaxValueValidator(2), MinValueValidator(-2)])

    def __str__(self):
        return f"Settings for FormTemplate ID: {self.form_template.id}"

templates/dashboard.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Talk2Form Forms Dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/@phosphor-icons/web"></script>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <script>
        function dismissMessage(element) {
            element.parentNode.removeChild(element);
        }
    </script>
</head>
<body>
    <div class="header">
        <h1>Dashboard</h1>
    </div>
    <div class="dashboard-container">
        {% for message in messages %}
        {% if message.tags %} {# check if message has tags #}
            {% if message.tags == 'success' %}
                <div class="message success-message">
                    <span>{{ message }}</span>
                    <button class="dismiss-button" onclick="dismissMessage(this.parentNode)">
                        <i class="ph ph-x"></i>
                    </button>
                </div>
            {% elif message.tags == 'error' %}
                <div class="message error-message">
                    <span>{{ message }}</span>
                    <button class="dismiss-button" onclick="dismissMessage(this.parentNode)">
                        <i class="ph ph-x"></i>
                    </button>
                </div>
            {% endif %}
        {% else %}
            <div class="message error-message">
                <span>{{ message }}</span>
                <button class="dismiss-button" onclick="dismissMessage(this.parentNode)">
                    <i class="ph ph-x"></i>
                </button>
            </div>
        {% endif %}
        {% endfor %}
        {% for form_template in form_templates %}
        <a class="form-link" href="{% url 'editform' form_template.id %}"><span>{{ form_template.title }}</span><i class="ph ph-arrow-circle-right"></i></a>
        {% endfor %}
    </div>
    <footer>
        <div class="bottom-icons">
            <a class="icon" href="logout"><i class="ph ph-sign-out"></i></a>
            <form method="POST" class="center-button-form" action="{% url 'create_default_form_template' %}">
                {% csrf_token %}
                <a href="dashboard" onclick="event.preventDefault(); this.closest('form').submit();" class="icon new-object-icon"><i class="ph ph-plus"></i></a>
            </form>
            <a class="icon" href="usersettings"><i class="ph ph-user-circle"></i></a>
        </div>
    </footer>
</body>
</html>

templates/editform.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Talk2Form Form</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/@phosphor-icons/web"></script>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <script>
        function dismissMessage(element) {
            element.parentNode.removeChild(element);
        }

        function openModal() {
            var modal = document.getElementById("formConfigModal");
            modal.style.display = "block";
        }

        function closeModal() {
            var modal = document.getElementById("formConfigModal");
            modal.style.display = "none";
        }

        window.addEventListener("click", function(event) {
            var modal = document.getElementById("formConfigModal");
            if (event.target === modal) {
            closeModal();
            }
        });

        function confirmDeleteFormTemplate() {
            var deleteBtn = document.getElementById('deleteFormTemplateBtn');
            var warningText = document.getElementById('deleteFormTemplateWarning');
            var confirmBtn = document.getElementById('confirmDeleteFormTemplateBtn');

            deleteBtn.style.display = 'none';
            warningText.style.display = 'block';
            confirmBtn.style.display = 'block';
        }

        function updateCharacterCount(input) {
            var maxLength = 255;
            var currentLength = input.value.length;
            var counter = document.getElementById("character_count");
            counter.textContent = currentLength + "/" + maxLength;
        }
        
        function resizeTextarea(textarea) {
            textarea.style.height = "auto";
            textarea.style.height = textarea.scrollHeight + "px";
        }
        
        function initializeTextarea(textareaId) {
            var textarea = document.getElementById(textareaId);
            resizeTextarea(textarea);
            
            textarea.addEventListener("input", function() {
                resizeTextarea(this);
            });
        }
    </script>
</head>
<body>
    <div class="form-container">
        {% for message in messages %}
        {% if message.tags %} {# check if message has tags #}
            {% if message.tags == 'success' %}
                <div class="message success-message">
                    <span>{{ message }}</span>
                    <button class="dismiss-button" onclick="dismissMessage(this.parentNode)">
                        <i class="ph ph-x"></i>
                    </button>
                </div>
            {% elif message.tags == 'error' %}
                <div class="message error-message">
                    <span>{{ message }}</span>
                    <button class="dismiss-button" onclick="dismissMessage(this.parentNode)">
                        <i class="ph ph-x"></i>
                    </button>
                </div>
            {% endif %}
        {% else %}
            <div class="message error-message">
                <span>{{ message }}</span>
                <button class="dismiss-button" onclick="dismissMessage(this.parentNode)">
                    <i class="ph ph-x"></i>
                </button>
            </div>
        {% endif %}
        {% endfor %}
        <!-- Header -->
        <div class="question-form-header">
            {% if editing_title %}
                <form method="POST" action="{% url 'save_template_title' form_template.id %}">
                    {% csrf_token %}
                    <textarea id="title-editing" class="title-editing" type="text" name="title" autofocus>{{ form_template.title }}</textarea>
                    <button type="submit">Save</button>
                </form>
            {% else %}
                <span>{{ form_template.title }}</span>
                <div class="form-header-icons">
                    <a href="{% url 'edit_template_title' form_template.id %}">
                        <i class="ph ph-pencil-simple"></i>
                    </a>
                    <a class="form-header-icon" href="#" onclick="openModal()">
                        <i class="ph ph-gear"></i>
                    </a>                  
                </div>
            {% endif %}
        </div>
        <!-- End Header -->

        <!-- Body -->
        <div class="question-form-body">
            {% if form_template.body %}
                {% if editing_body %}
                    <form method="POST" action="{% url 'save_template_body' form_template.id %}">
                        {% csrf_token %}
                        <textarea id="body-editing" class="body-editing" type="text" name="body" autofocus>{{ form_template.body }}</textarea>
                        <button type="submit">Save</button>
                    </form>
                {% else %}
                    <div class="form-template-body">{{ form_template.body }}</div>
                    <div class="form-header-icons">
                        <a href="{% url 'edit_template_body' form_template.id %}">
                            <i class="ph ph-pencil-simple"></i>
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <!-- End Body -->

        {% for question in form_template.question_set.all|dictsort:'id' %}
        <div class="combined-form">
            <div class="question-form">
                {% if question.editing %}
                    <div class="form-edit-buttons">
                        <form method="POST" action="{% url 'save_question' form_template.id question.id %}">
                            {% csrf_token %}
                            <textarea id="question-editing-{{ question.id }}" class="question-editing" name="question" autofocus>{{ question.question }}</textarea>
                            <button type="submit" class="save-button"><i class="ph-bold ph-floppy-disk"></i></button>
                        </form>
                    </div>
                {% else %}
                    <span class="question-text">{{ question.question }}</span>
                    <a class="form-edit" href="{% url 'edit_question' form_template.id question.id %}">
                        <i class="ph-bold ph-pencil-simple"></i>
                    </a>
                    <form method="POST" action="{% url 'delete_question' form_template.id question.id %}">
                        {% csrf_token %}
                        <a class="form-edit" onclick="event.preventDefault(); this.closest('form').submit();">
                            <i class="ph-bold ph-trash"></i>
                        </a>
                    </form>
                {% endif %}
            </div>
            <div class="response-box"></div>
        </div>
        <script>
            initializeTextarea("question-editing-{{ question.id }}");
        </script>
        {% endfor %}
    </div>
    <!-- Modal -->
    <div id="formConfigModal" class="modal">
        <div class="modal-content">
            <h2>Edit Form Configuration</h2>
            <form id="formConfigForm" method="POST" action="{% url 'save_form_config' form_template.id %}">
                {% csrf_token %}
                <div class="form-field">
                    <label for="language">Language:</label>
                    <select id="language" name="language">
                        <option value="english" {% if form_config.language == 'english' %}selected{% endif %}>English</option>
                        <option value="chinese" {% if form_config.language == 'chinese' %}selected{% endif %}>Chinese</option>
                        <option value="spanish" {% if form_config.language == 'spanish' %}selected{% endif %}>Spanish</option>
                        <option value="hindi" {% if form_config.language == 'hindi' %}selected{% endif %}>Hindi</option>
                        <option value="marathi" {% if form_config.language == 'marathi' %}selected{% endif %}>Marathi</option>
                        <option value="japanese" {% if form_config.language == 'japanese' %}selected{% endif %}>Japanese</option>
                        <option value="korean" {% if form_config.language == 'korean' %}selected{% endif %}>Korean</option>
                        <!-- Add other language options here -->
                    </select>
                </div>
                <div class="form-field">
                    <label for="conversation_type">Conversation Type:</label>
                    <input type="text" id="conversation_type" name="conversation_type" maxlength="255" oninput="updateCharacterCount(this)" value="{{ form_config.conversation_type }}">
                    <span id="character_count" class="character_count">0/255</span>
                </div>                
                <div class="form-field">
                    <label for="audio_recognition_model_id">Audio Recognition Model:</label>
                    <select id="audio_recognition_model_id" name="audio_recognition_model_id">
                        <option value="whisper-1" {% if form_config.audio_recognition_model_id == 'whisper-1' %}selected{% endif %}>Whisper</option>
                        <!-- Add other audio recognition model options here -->
                    </select>
                </div>
                <div class="form-field">
                    <label for="system_prompt">System Prompt:</label>
                    <textarea id="system_prompt" name="system_prompt" maxlength="5000">{{ form_config.system_prompt }}</textarea>
                </div>
                <div class="form-field">
                    <label for="ai_model_id">AI Model:</label>
                    <select id="ai_model_id" name="ai_model_id">
                        <option value="gpt-5" {% if form_config.ai_model_id == 'gpt-5' %}selected{% endif %}>GPT-5</option>
                        <option value="gpt-5-mini" {% if form_config.ai_model_id == 'gpt-5-mini' %}selected{% endif %}>GPT-5 Mini</option>
                        <option value="gpt-4.1" {% if form_config.ai_model_id == 'gpt-4.1' %}selected{% endif %}>GPT-4.1</option>
                        <!-- Add other AI model options here -->
                    </select>
                </div>
                <div class="form-field">
                    <label for="temperature">Temperature:</label>
                    <input type="number" id="temperature" name="temperature" step="0.1" min="-2" max="2" value="{{ form_config.temperature }}">
                </div>
                <div class="form-field">
                    <label for="presence_penalty">Presence Penalty:</label>
                    <input type="number" id="presence_penalty" name="presence_penalty" step="0.1" min="-2" max="2" value="{{ form_config.presence_penalty }}">
                </div>
                <div class="button-container">
                    <button class="settings-button save" type="submit">Save</button>
                    <button class="settings-button cancel" onclick="closeModal()">Cancel</button>
                </div>
            </form>
            <form id="deleteFormTemplateForm" action="{% url 'delete_form_template' form_template.id %}" method="POST">
                {% csrf_token %}
                <button id="deleteFormTemplateBtn" class="settings-button danger" type="button" onclick="confirmDeleteFormTemplate()">Delete Form Template</button>
                <p id="deleteFormTemplateWarning" style="display: none;"><b>Are you sure?</b> <br> <span style="color:rgb(209, 71, 71);">Deleting a form template will delete all associated form responses.</span></p>
                <button id="confirmDeleteFormTemplateBtn" class="settings-button danger" type="submit" style="display: none;">Confirm Deletion</button>
            </form>
        </div>
    </div>
    <script>
        initializeTextarea("body-editing");
        initializeTextarea("title-editing");
    </script>
        
</body>
<footer>
    <div class="bottom-icons">
        <a class="icon" href="/dashboard"><i class="ph ph-arrow-u-up-left"></i></a>
        <form method="POST" class="center-button-form" action="{% url 'create_question' form_template.id %}">
            {% csrf_token %}
            <a href="" onclick="event.preventDefault(); this.closest('form').submit();" class="icon new-object-icon"><i class="ph ph-plus"></i></a>
        </form>
        <a class="icon" href="{% url 'create_form' form_template.id %}"><i class="ph ph-microphone"></i></a>
    </div>
</footer>
</html>

templates/record.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html>
<head>
    <title>Form Created</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/@phosphor-icons/web"></script>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
        <div class="form-container">
            <!-- Header -->
            <div class="question-form-header">
                {% if editing_title %}
                    <form method="POST" action="{% url 'save_template_title' form_template.id %}">
                        {% csrf_token %}
                        <textarea id="title-editing" class="title-editing" type="text" name="title" autofocus>{{ form_template.title }}</textarea>
                        <button type="submit">Save</button>
                    </form>
                {% else %}
                    <span>{{ form_template.title }}</span>
                    <div class="form-header-icons">
                        <a href="#">
                            <i class="ph ph-pencil-simple"></i>
                        </a>
                        <a class="form-header-icon" href="#" onclick="openModal()">
                            <i class="ph ph-gear"></i>
                        </a>                  
                    </div>
                {% endif %}
            </div>
            <!-- End Header -->
    
            <!-- Body -->
            <div class="question-form-body">
                {% if form_template.body %}
                    {% if editing_body %}
                        <form method="POST" action="{% url 'save_template_body' form_template.id %}">
                            {% csrf_token %}
                            <textarea id="body-editing" class="body-editing" type="text" name="body" autofocus>{{ form_template.body }}</textarea>
                            <button type="submit">Save</button>
                        </form>
                    {% else %}
                        <div class="form-template-body">{{ form_template.body }}</div>
                        <div class="form-header-icons">
                            <a href="{% url 'edit_template_body' form_template.id %}">
                                <i class="ph ph-pencil-simple"></i>
                            </a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
            <!-- End Body -->
            <!-- Start Questions -->
            {% for question in form_template.question_set.all|dictsort:'id' %}
            <div class="combined-form">
                <div class="question-form">
                    {% if question.editing %}
                        <div class="form-edit-buttons">
                            <form method="POST" action="{% url 'save_question' form_template.id question.id %}">
                                {% csrf_token %}
                                <textarea id="question-editing-{{ question.id }}" class="question-editing" name="question" autofocus>{{ question.question }}</textarea>
                                <button type="submit" class="save-button"><i class="ph-bold ph-floppy-disk"></i></button>
                            </form>
                        </div>
                    {% else %}
                        <span class="question-text">{{ question.question }}</span>
                        <a class="form-edit" href="{% url 'edit_question' form_template.id question.id %}">
                            <i class="ph-bold ph-pencil-simple"></i>
                        </a>
                        <form method="POST" action="{% url 'delete_question' form_template.id question.id %}">
                            {% csrf_token %}
                            <a class="form-edit" onclick="event.preventDefault(); this.closest('form').submit();">
                                <i class="ph-bold ph-trash"></i>
                            </a>
                        </form>
                    {% endif %}
                </div>
                <div class="response-box"></div>
            </div>
            {% endfor %}
            <!-- End Questions -->
        </div>
    <div class="modal-background"></div>
    <div class="modal-container">
        <div class="recording-icons">
            <h2>Record Conversation</h2>
            <div id="recording-time">0:00 / 30:00</div>
            <button id="start-btn" class="start-btn">
                <i class="ph ph-microphone"></i>
            </button>
            <button id="pause-btn" class="pause-btn" style="display: none;">
                <i class="ph ph-pause"></i>
            </button>
            <button id="resume-btn" class="resume-btn" style="display: none;">
                <i class="ph ph-play"></i>
            </button>
            <button id="stop-btn" class="stop-btn" style="display: none;">
                <i class="ph ph-stop"></i>
            </button>
        </div>
    </div>
    <script>
        const csrfToken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;

        const formId = '{{ form.id }}';
        const startBtn = document.getElementById('start-btn');
        const stopBtn = document.getElementById('stop-btn');
        const pauseBtn = document.getElementById('pause-btn');
        const resumeBtn = document.getElementById('resume-btn');
        const recordingTimeElement = document.getElementById('recording-time');

        let mediaRecorder; // MediaRecorder object
        let startTime;
        let intervalId;
        let elapsedTime = 0;

        startBtn.addEventListener('click', startRecording);
        stopBtn.addEventListener('click', stopRecording);
        pauseBtn.addEventListener('click', pauseRecording);
        resumeBtn.addEventListener('click', resumeRecording);

        function startRecording() {
            startBtn.style.display = 'none'; // Hide the start button
            pauseBtn.style.display = 'inline-block'; // Show the pause button
            stopBtn.style.display = 'inline-block';

            navigator.mediaDevices.getUserMedia({ audio: true })
                .then(function(stream) {
                    let mimeType = 'audio/webm; codec=opus';
                    let dataType = 'webm';
                    if (!MediaRecorder.isTypeSupported(mimeType)) {
                        mimeType = 'audio/mp4; codec=aac';
                        dataType = 'mp4';
                    }
                    mediaRecorder = new MediaRecorder(stream, { mimeType: mimeType });
                    mediaRecorder.addEventListener('dataavailable', function(e) {
                        if (e.data.size > 0) {
                            sendAudioChunk(e.data, dataType); // Send the chunk to the server
                        }
                    });
                    mediaRecorder.start();
                    startTime = new Date().getTime();
                    intervalId = setInterval(updateRecordingTime, 1000);
                    setTimeout(stopRecording, 1800000)
                })
                .catch(function(err) {
                    console.error('Error accessing microphone:', err);
                });
        }

        function stopRecording() {
            if (mediaRecorder && mediaRecorder.state !== 'inactive') {
                mediaRecorder.stop();
                mediaRecorder.stream.getTracks().forEach(function(track) {
                    track.stop();
                });
                clearInterval(intervalId);
            }
        }

        function pauseRecording() {
            if (mediaRecorder && mediaRecorder.state === 'recording') {
                mediaRecorder.pause();
                clearInterval(intervalId); // Pause the timer
                elapsedTime = new Date().getTime() - startTime;
                pauseBtn.style.display = 'none'; // Hide the pause button
                resumeBtn.style.display = 'inline-block'; // Show the resume button
            }
        }

        function resumeRecording() {
            if (mediaRecorder && mediaRecorder.state === 'paused') {
                mediaRecorder.resume();
                startTime = new Date().getTime() - elapsedTime; // Update the start time
                intervalId = setInterval(updateRecordingTime, 1000); // Resume the timer
                resumeBtn.style.display = 'none'; // Hide the resume button
                pauseBtn.style.display = 'inline-block'; // Show the pause button
            }
        }

        function sendAudioChunk(chunk, dataType) {
            const formData = new FormData();
            formData.append('audioChunk', chunk);
            formData.append('form_id', formId);
            formData.append('dataType', dataType);
            formData.append('csrfmiddlewaretoken', csrfToken);

            fetch(`/stop_audio/${formId}/`, {
                method: 'POST',
                body: formData
            })
            .then(function(response) {
                response.json().then(function(json){console.log(json)});
                window.location.href = `/response_form/${formId}/`;
                chunk = null;
            })
            .catch(function(error) {
                console.error('Error sending audio chunk:', error);
            });
        }

        function updateRecordingTime() {
            const currentTime = new Date().getTime();
            const elapsedTime = currentTime - startTime;
            const maxRecordingTime = 1800000; // 30 minutes in milliseconds
            const remainingTime = Math.max(maxRecordingTime - elapsedTime, 0);
            const currentMinutes = Math.floor(elapsedTime / 60000);
            const currentSeconds = Math.floor((elapsedTime % 60000) / 1000);
            const maxMinutes = Math.floor(maxRecordingTime / 60000);
            const maxSeconds = Math.floor((maxRecordingTime % 60000) / 1000);
            recordingTimeElement.textContent = `${currentMinutes}:${currentSeconds.toString().padStart(2, '0')} / ${maxMinutes}:${maxSeconds.toString().padStart(2, '0')}`;
        }
    </script>
</body>
</html>